INSERT INTO photos(photo, title, location, taken_date, capture) VALUES('https://images.unsplash.com/photo-1523595857-fe9ee689f76f?ixlib=rb-1.2.1&auto=format&fit=crop&w=3367&q=80', 'Palm Trees', 'Long Beach', '12/09/2015', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit');
INSERT INTO photos(photo, title, location, taken_date, capture) VALUES('https://images.unsplash.com/photo-1518677390127-f6397672f632?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=3302&q=80', 'California Vibes', 'Santa Monica', '15/09/2015', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit');
INSERT INTO photos(photo, title, location, taken_date, capture) VALUES('https://images.unsplash.com/photo-1502836409737-232b37c6716d?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1301&q=80', 'Surf', 'Venice Beach', '18/09/2015', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit');

INSERT INTO photos(photo, title, location, taken_date, capture) VALUES('https://i1.wp.com/nyibeercompetition.com/wp-content/uploads/2015/04/pixasquare-700115-unsplash.jpg?w=1320&ssl=1', 'Big City', 'NY', '20/10/2015', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit');
INSERT INTO photos(photo, title, location, taken_date, capture) VALUES('https://images.unsplash.com/photo-1465925508512-1e7052bb62e6?ixlib=rb-1.2.1&auto=format&fit=crop&w=934&q=80', 'beep-beep!', 'NY', '15/10/2015', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit');
INSERT INTO photos(photo, title, location, taken_date, capture) VALUES('https://images.unsplash.com/photo-1518103744022-a2121047f429?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=60', 'NIGHT', 'NY', '22/10/2015', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit');

INSERT INTO photos(photo, title, location, taken_date, capture) VALUES('https://images.unsplash.com/photo-1513568720563-6a5b8c6caab3?ixlib=rb-1.2.1&auto=format&fit=crop&w=2227&q=80', 'busy!', 'Bangkok', '23/09/2016', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit');
INSERT INTO photos(photo, title, location, taken_date, capture) VALUES('https://idealmagazine.co.uk/wp-content/uploads/2018/04/lisheng-chang-396821-unsplash.jpg', 'Floating Market', 'Chiang Mai', '26/09/2016', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit');
INSERT INTO photos(photo, title, location, taken_date, capture) VALUES('https://images.unsplash.com/photo-1520882948759-529963a84160?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=60', 'Flowers', 'Ko Samui', '28/09/2016', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit');

INSERT INTO photos(photo, title, location, taken_date, capture) VALUES('https://images.unsplash.com/photo-1505440484611-23c171ad6e96?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2237&q=80', 'Maiko', 'Kyoto', '07/03/2017', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit');
INSERT INTO photos(photo, title, location, taken_date, capture) VALUES('https://images.unsplash.com/photo-1513742734373-55e92ab38e3b?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=60', 'Troi Gate', 'Kyoto', '28/02/2019', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit');
INSERT INTO photos(photo, title, location, taken_date, capture) VALUES('https://images.unsplash.com/photo-1493997181344-712f2f19d87a?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=60', 'Roji-Ura', 'Kyoto', '05/03/2017', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit');

INSERT INTO photos(photo, title, location, taken_date, capture) VALUES('https://images.unsplash.com/photo-1520377119034-bce40caae9a5?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2250&q=80', 'Bonjour', 'Paris', '28/07/2018', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit');
INSERT INTO photos(photo, title, location, taken_date, capture) VALUES('https://blog-content.thestorefront.com/mag/wp-content/uploads/2019/02/earth-608350-unsplash-768x960.jpg', 'voiLa!', 'Paris', '30/07/2018', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit');
INSERT INTO photos(photo, title, location, taken_date, capture) VALUES('https://images.unsplash.com/photo-1532081000137-2bd921a97119?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=60', 'Coffee Time', 'Paris', '01/08/2019', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit');

INSERT INTO photos(photo, title, location, taken_date, capture) VALUES('https://images.unsplash.com/photo-1461937995729-a2e442122d18?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1000&q=80', 'Playita', 'Mallorca', '01/08/2018', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit');
INSERT INTO photos(photo, title, location, taken_date, capture) VALUES('https://images.unsplash.com/photo-1490606920905-635add8bdad2?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=60', 'Veraniego', 'Cadiz', '04/08/2018', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit');
INSERT INTO photos(photo, title, location, taken_date, capture) VALUES('https://images.unsplash.com/photo-1530127796739-53cf66b0e64d?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=60', 'Buenas', 'Rota', '08/08/2019', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit');
